#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/deploy/hostinger-production.env"
source "$ROOT/deploy/secrets.env"
cat > "$OUT" <<EOF
NODE_ENV=production
DATABASE_URL=${DATABASE_URL}
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION:-15m}
JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-7d}
API_PREFIX=${API_PREFIX:-api/v1}
CORS_ORIGINS=${CORS_ORIGINS:-$WEB_URL}
SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
SUPER_ADMIN_NAME=${SUPER_ADMIN_NAME:-Super Admin}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
HOSTINGER_COMBINED=1
INTERNAL_API_URL=${INTERNAL_API_URL:-http://127.0.0.1:4001}
API_INTERNAL_PORT=${API_INTERNAL_PORT:-4001}
EOF
echo "✅ Wrote $OUT (gitignored — upload to Hostinger env import)"
