const WORD_MAP: Record<string, string> = {
  muhammad: 'محمد',
  mohammad: 'محمد',
  mohammed: 'محمد',
  muhammed: 'محمد',
  umar: 'عمر',
  ali: 'علی',
  ahmed: 'احمد',
  ahmad: 'احمد',
  hassan: 'حسن',
  hasan: 'حسن',
  husain: 'حسین',
  hussain: 'حسین',
  fatima: 'فاطمہ',
  aysha: 'عائشہ',
  ayesha: 'عائشہ',
  aisha: 'عائشہ',
  khadija: 'خدیجہ',
  abdul: 'عبد',
  rehman: 'رحمن',
  rahman: 'رحمن',
  karim: 'کریم',
  kareem: 'کریم',
  khan: 'خان',
  malik: 'مالک',
  shah: 'شاہ',
  shaikh: 'شیخ',
  sheikh: 'شیخ',
  syed: 'سید',
  sayed: 'سید',
  saeed: 'سعید',
  said: 'سعید',
  bilal: 'بلال',
  usman: 'عثمان',
  uthman: 'عثمان',
  osman: 'عثمان',
  hamza: 'حمزہ',
  hamzah: 'حمزہ',
  imran: 'عمران',
  asif: 'آصف',
  ashraf: 'اشرف',
  nadeem: 'ندیم',
  naeem: 'نعیم',
  saleem: 'سلیم',
  salim: 'سلیم',
  rauf: 'رؤف',
  raouf: 'رؤف',
  raza: 'رضا',
  rizwan: 'رضوان',
  riaz: 'رضا',
  riyaz: 'رضا',
  akram: 'اکرم',
  arif: 'عارف',
  amir: 'امیر',
  aamir: 'امیر',
  anwar: 'انور',
  azam: 'اعظم',
  azhar: 'اظہر',
  bashir: 'بشیر',
  farhan: 'فرحان',
  faisal: 'فیصل',
  fayyaz: 'فیاض',
  ghulam: 'غلام',
  gul: 'گل',
  hafeez: 'حفیظ',
  hafiz: 'حافظ',
  hanif: 'حنیف',
  haroon: 'ہارون',
  harun: 'ہارون',
  hashim: 'ہاشم',
  ibrahim: 'ابراہیم',
  idrees: 'ادریس',
  iqbal: 'اقبال',
  irfan: 'عرفان',
  ishaq: 'اسحاق',
  ismail: 'اسماعیل',
  javed: 'جاوید',
  jawed: 'جاوید',
  kamran: 'کامران',
  kashif: 'کاشف',
  khalid: 'خالد',
  latif: 'لطیف',
  liaqat: 'لیاقت',
  liaquat: 'لیاقت',
  majid: 'مجید',
  masood: 'مسعود',
  masud: 'مسعود',
  mehmood: 'محمود',
  mahmood: 'محمود',
  mohsin: 'محسن',
  munir: 'منیر',
  murad: 'مراد',
  mustafa: 'مصطفی',
  naseem: 'نسیم',
  nasir: 'ناصر',
  nawaz: 'نواز',
  niaz: 'نیاز',
  noor: 'نور',
  parveen: 'پروین',
  parween: 'پروین',
  qadir: 'قادر',
  qasim: 'قاسم',
  rafiq: 'رفیق',
  rahim: 'رحیم',
  raheel: 'راحیل',
  rashid: 'راشد',
  sajid: 'ساجد',
  sami: 'سمی',
  saqlain: 'ثقلین',
  shabbir: 'شبیر',
  shafiq: 'شفیق',
  shakir: 'شاکر',
  shaukat: 'شوکت',
  shoaib: 'شعیب',
  sohail: 'سہیل',
  suhail: 'سہیل',
  sultan: 'سلطان',
  tahir: 'طاہر',
  tariq: 'طارق',
  ubaid: 'عبید',
  wahid: 'واحد',
  waqar: 'وقار',
  waqas: 'وقاص',
  waseem: 'وسیم',
  wasim: 'وسیم',
  yasir: 'یاسر',
  yasmin: 'یاسمین',
  yusuf: 'یوسف',
  yousuf: 'یوسف',
  zafar: 'ظفر',
  zahid: 'زاہد',
  zain: 'زین',
  zeeshan: 'ذیشان',
  zubair: 'زبیر',
  zubayr: 'زبیر',
  abbas: 'عباس',
  abdullah: 'عبداللہ',
  abdulrehman: 'عبدالرحمن',
  abdulrahman: 'عبدالرحمن',
  abdulqadir: 'عبدالقادر',
  abdulkarim: 'عبدالکریم',
  abdulghaffar: 'عبدالغفار',
  abdulghani: 'عبدالغنی',
  abdulhameed: 'عبدالحمید',
  abduljabbar: 'عبدالجبار',
  abdulmajid: 'عبدالمجید',
  abdulmalik: 'عبدالمالک',
  abdulsattar: 'عبدالستار',
  abdulwaheed: 'عبدالواحد',
  bibi: 'بی بی',
  begum: 'بیگم',
  mian: 'میاں',
  chaudhry: 'چودھری',
  chaudhary: 'چودھری',
  chaudry: 'چودھری',
  rajput: 'راجپوت',
  arain: 'آرائیں',
  jutt: 'جٹ',
  jatt: 'جٹ',
  gujjar: 'گجر',
  ansari: 'انصاری',
  qureshi: 'قریشی',
  mirza: 'مرزا',
  baig: 'بیگ',
  bhatti: 'بھٹی',
  wattoo: 'وٹو',
  rana: 'رانا',
  dogar: 'دوگر',
  tarar: 'تارڑ',
  sial: 'سيال',
  cheema: 'چیمہ',
  lahore: 'لاہور',
  karachi: 'کراچی',
  islamabad: 'اسلام آباد',
  faisalabad: 'فیصل آباد',
  multan: 'ملتان',
  peshawar: 'پشاور',
  rawalpindi: 'راولپنڈی',
  sialkot: 'سیالکوت',
  gujranwala: 'گوجرانوالہ',
  sargodha: 'سرگودھا',
  bahawalpur: 'بہاولپور',
  sahiwal: 'ساہِوال',
  okara: 'اوکرا',
  kasur: 'قصور',
  sheikhupura: 'شیخوپura',
  jhang: 'جhang',
  mianwali: 'Mianwali',
  attock: 'اٹک',
  chakwal: 'چکوال',
  narowal: 'نarowal',
  pakpattan: 'Pakpattan',
  vehari: 'Vehari',
  khanewal: 'خانیوال',
  lodhran: 'Lodhran',
  muzaffargarh: 'Muzaffargarh',
  rahimyar: 'Rahim Yar Khan',
  dera: 'ڈera',
  ghazi: 'غازی',
  shop: 'دکان',
  store: 'اسٹور',
  mobile: 'موبائل',
  phone: 'فون',
  electrician: 'الیکٹریشن',
  mechanic: 'مکینک',
  driver: 'ڈرائیور',
  farmer: 'کسان',
  teacher: 'استاد',
  student: 'طالب علم',
  labour: 'مزدور',
  labor: 'مزدور',
  worker: 'مزدور',
  business: 'کاروبار',
  trader: 'تاجر',
  shopkeeper: 'دکاندار',
  address: 'پتہ',
  street: 'گلی',
  bazaar: 'بازار',
  bazar: 'بازار',
  mohalla: 'محلہ',
  colony: 'کالونی',
  house: 'گھر',
  road: 'سڑک',
};

const SYLLABLES: [string, string][] = [
  ['sh', 'ش'],
  ['kh', 'خ'],
  ['gh', 'غ'],
  ['ch', 'چ'],
  ['th', 'تھ'],
  ['dh', 'دھ'],
  ['bh', 'بھ'],
  ['ph', 'پھ'],
  ['zh', 'ژ'],
  ['aa', 'آ'],
  ['ee', 'ی'],
  ['oo', 'و'],
  ['ai', 'ے'],
  ['au', 'ؤ'],
  ['ei', 'ے'],
  ['ou', 'و'],
  ['ng', 'نگ'],
  ['a', 'ا'],
  ['b', 'ب'],
  ['c', 'ک'],
  ['d', 'د'],
  ['e', 'ی'],
  ['f', 'ف'],
  ['g', 'گ'],
  ['h', 'ہ'],
  ['i', 'ی'],
  ['j', 'ج'],
  ['k', 'ک'],
  ['l', 'ل'],
  ['m', 'م'],
  ['n', 'ن'],
  ['o', 'و'],
  ['p', 'پ'],
  ['q', 'ق'],
  ['r', 'ر'],
  ['s', 'س'],
  ['t', 'ت'],
  ['u', 'و'],
  ['v', 'و'],
  ['w', 'و'],
  ['x', 'کس'],
  ['y', 'ی'],
  ['z', 'ز'],
];

function normalizeRoman(input: string): string {
  return input.trim().toLowerCase().replace(/[^a-z\s'-]/g, '');
}

function transliterateWord(word: string): string {
  const key = word.replace(/['-]/g, '');
  if (!key) return word;
  if (WORD_MAP[key]) return WORD_MAP[key];

  let result = '';
  let i = 0;
  while (i < key.length) {
    let matched = false;
    for (const [roman, urdu] of SYLLABLES) {
      if (key.startsWith(roman, i)) {
        result += urdu;
        i += roman.length;
        matched = true;
        break;
      }
    }
    if (!matched) {
      result += key[i];
      i += 1;
    }
  }
  return result;
}

export function romanToUrdu(input: string): string {
  const normalized = normalizeRoman(input);
  if (!normalized) return '';

  return normalized
    .split(/\s+/)
    .filter(Boolean)
    .map(transliterateWord)
    .join(' ')
    .trim();
}

export function containsUrduScript(text: string): boolean {
  return /[\u0600-\u06FF]/.test(text);
}
